# The tag index pages can be auto created as well.
# tag > mkdir
# [tag]/index.html created with specific link:
#                  href=[path]/[title]/[page]


Data =
{ path: "page",
  pages: [
    { page: "01", title: 'void', tag: [ :journal ] },
    { page: "02", title: "here's what happens when you read the bible", tag: [ :journal, :bible ] },
    { page: "03", title: "4D blogging", tag: [ :journal ] },
    { page: "04", title: "Consuming vs. Producing", tag: [ :journal ] },
    { page: "05", title: "Letter to Grandma", tag: [ :journal ] },
    { page: "06", title: "Fire CSS", tag: [ :css, :code ] },
    { page: "07", title: "Math", tag: [ :demo ] },
    { page: "09", title: "Flipper CSS", tag: [ :css, :code ] },
    { page: "10", title: "English Defers to Hebrew", tag: [ :journal, :bible ] },
    { page: "11", title: "Bowl Soul Whole", tag: [:poem, :journal ] },
    { page: "12", title: "Squares CSS", tag: [ :css, :code ] },
    { page: "13", title: "Postgresql", tag: [ :code, :postgres ] },
    { page: "14", title: "Learning to Code", tag: [ :journal, :code ] },
    { page: "15", title: "What is wrong with truth?", tag: [ :journal ] },
    { page: "16", title: "6 months to 40", tag: [ :journal ] },
    { page: "17", title: "Buttered Toast", tag: [:poem, :journal ] },
    { page: "18", title: "Creation", tag: [ :journal ] },
    { page: "19", title: "Farmer Brown", tag: [ :journal ] },
    { page: "20", title: "Moment", tag: [ :journal ] },
    { page: "21", title: "Inspiration for Moment", tag: [ :journal ] },
    { page: "22", title: "Malachi to Music", tag: [ :journal ] },
    { page: "23", title: "Origin", tag: [ :journal ] },
    { page: "24", title: "poop", tag: [ :journal ] },
    { page: "25", title: "Psalms 11 to ours", tag: [ :journal, :bible ] },
    { page: "26", title: "Questions", tag: [ :journal ] },
    { page: "27", title: "the Bible", tag: [ :journal ] },
    { page: "28", title: "The big Game", tag: [ :journal ] },
    { page: "29", title: "the Point", tag: [ :journal ] },
    { page: "30", title: "The World", tag: [ :journal ] },
    { page: "31", title: "Winter", tag: [ :journal ] },
    { page: "32", title: "How I'm learning to Love", tag: [ :journal, :genesis, :bible ] },
    { page: "33", title: "What is the Problem", tag: [ :journal ] },
    { page: "34", title: "Linux low level!", tag: [:code ] },
    { page: "35", title: "Do Due New Nueue", tag: [:todo ], nav: [:main] },
    { page: "36", title: "Ruby File Management", tag: [:demo, :code ] },
    { page: "37", title: "Tick, Time Management", tag: [ :me, :demo ] },
    { page: "38", title: "Routines", tag: [ :me ] },
    { page: "39", title: "Proverbs", tag: [ :proverbs, :bible, :dadzoo ] },
    { page: "", title: "(coming soon) Metaprogramming in Ruby", tag: [ :code ] },
    { page: "", title: "(coming soon) VIM", tag: [ :code ] },
    { page: "", title: "(coming soon) Building Command line Apps", tag: [ :code ] },
    { page: "", title: "(coming soon) Teraform", tag: [ :code ] },
    { page: "", title: "(coming soon) RabbitMQ", tag: [ :code ] },
    { page: "", title: "(coming soon) Elastic Search", tag: [ :code ] },
    { page: "", title: "(coming soon) Dev Ops", tag: [:code ] },
    { page: "", title: "(coming soon) Teraform", tag: [:code ] },
    { page: "", title: "(coming soon) Elixir", tag: [:code ] },
    { page: "", title: "(coming soon) Jenkins", tag: [:code ] },
    { page: "", title: "(coming soon) AWS", tag: [:code ] },
    { page: "", title: "(coming soon) RegEx", tag: [:code ] },
    { page: "", title: "(coming soon) Functional Programming", tag: [:code ] },
    { page: "", title: "(coming soon) Make files", tag: [:code ] },
    { page: "", title: "(coming soon) Make files", tag: [:code ] },
    { page: "", title: "(coming soon) Docker", tag: [:code ] },
    { page: "", title: "(coming soon) Micro Services", tag: [:code ] },
  ]
}
